# Generated by Django 5.0.6 on 2026-06-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("uae", "United Arab Emirates"),
                            ("us", "United States"),
                        ],
                        default="uae",
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180)),
                (
                    "icon",
                    models.CharField(
                        default="🧬",
                        help_text="An emoji or short glyph shown on cards.",
                        max_length=8,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="One-line description used on cards and meta tags.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full description. Separate paragraphs with a blank line."
                    ),
                ),
                (
                    "benefits",
                    models.TextField(
                        blank=True,
                        help_text="One benefit per line; rendered as a checklist.",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional starting price (in the region's currency).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=170)),
            ],
            options={
                "ordering": ["order", "name"],
                "unique_together": {("region", "slug")},
            },
        ),
    ]
